app/components/AdminLogin.tsx, app/page.tsx, app/styling/globals.css, package-lock.json, package.json
Used tailwind to create a login form.
=> Admin login

lib/models/StoreModel.ts, lib/models/UserModel.ts
=> Add store model

app/mystore/[slug]/products/create/page.js, app/mystore/[slug]/products/page.js, components/CreateProductForm.tsx, utils/actions/productActions.ts
created a mock form and page for testing create product action
=> Create mock create product form and page

lib/models/ProductModel.ts, lib/models/StoreAddress.ts
=> Create StoreAddress schema

app/mystore/[slug]/address/page.js, components/StoreAddressForm.tsx, utils/actions/productActions.ts, utils/actions/storeActions.ts
add example component and page
=> Add createStoreAddress Action

app/mystore/[slug]/address/edit/page.js, components/EditStoreAddressForm.tsx, utils/actions/productActions.ts, utils/actions/storeActions.ts
=> Add Edit Store Address Action

app/mystore/[slug]/page.js, app/mystore/[slug]/page.tsx, app/mystore/[slug]/products/page.js, app/mystore/[slug]/products/page.tsx, components/Navbar.tsx, components/ProductList.tsx, next.config.mjs, package-lock.json
* Using MaterialUI for new Navbar, icons and products: https://mui.com/material-ui/
* Updated config to allow images
* Update dependencies
* Navigation to Products and Homepage works for admin site for a given store
=> Updated Navbar to use mui + improved products page

lib/models/StoreStory.ts
This is a temporary Schema that will be adjusted to fit requirements
=> Create Store Story Schema

app/createstore/[slug]/page.js, app/createstore/[slug]/story/page.js, components/CreateStoreStoryForm.tsx, lib/models/StoreStoryModel.ts, utils/actions/storeActions.ts
store owner now has the ability to create a store story
=> Add ability to create a store story

app/mystore/[slug]/story/page.js, components/StoreStory.tsx, utils/actions/storeActions.ts
created example componet and page
=> Add getStoreStory action

app/mystore/[slug]/story/edit/page.js, components/EditStoreStoryForm.tsx, utils/actions/storeActions.ts
created example component and page
=> Add edit story action

app/createstore/[slug]/story/page.js, app/mystore/[slug]/story/edit/page.js, components/ProductList.tsx, components/create-forms/CreateProductForm.tsx, lib/models/StoreModel.ts
Change Image to img on product list
Removed unique to ownername in store schema
=> Add hidden input with store slug

app/mystore/[slug]/products/[product]/page.tsx, app/mystore/[slug]/products/page.tsx, components/ProductList.tsx, components/StoreStory.tsx
change Image to img on StoreStory component
=> Change name to slug in edit product link

app/styling/globals.css, components/LandingPage.tsx, components/Navbar.tsx, components/header/header.tsx
***NOTE: THE NAVBAR IS DIFFERENT FROM THE SIDEBAR COMPONENT
THE NAVBAR IS ONLY RENDERED ON THE LANDING / SPLASH PAGE, THE SIDE BAR BELONGS ON THE STORE-OWNER PAGE
Created Navbar component, imported it into LandingPage component so it only renders on that page. Might need to change in the future.
=> Created Navbar

app/mystore/[slug]/products/page.tsx, components/ProductList.tsx
Add product button works. Changed next `<Image/>` component back to `<img/>`. Able to add new products with images now.
=> Connected Add product button to product details page

middleware.ts, utils/actions/storeActions.ts
Proteced routes createstore, mystore
=> Add ability to turn on protected routes

components/MyStoreInfo.tsx, components/Sidebar.tsx
Add Store Address information to Store Info component
=> Add Info to Sidebar

app/mystore/[slug]/info/page.js, app/mystore/[slug]/page.tsx, app/mystore/[slug]/story/page.js, app/mystore/page.js, components/StoreStory.tsx, utils/actions/storeActions.ts
=> Add story to home and edit button

components/StoreSignUpForm.tsx, components/create-forms/CreateStoreAddressForm.tsx, components/create-forms/StoreStoryForm.tsx, utils/actions/storeActions.ts
Gracefully handle errors in StoreStory
=> Gracefully handle errors in StoreAddress

components/StoreSignUpForm.tsx
Changed Owner Name form field label to Owner First & Last Name on "Sign-up" form.
=> Changed Owner Name form field label to Owner First & Last Name

components/StoreSignUpForm.tsx
Added: 'Please fill out the form below to create your store' to the top of Sign Up Form.
=> Added instructions to Sign Up Form

components/MyStoreInfo.tsx
Added formatting with MUI Table Styling components to the MyStoreInfo page:
=> Formatted MyStoreInfo page

app/page.tsx, app/styling/globals.css, components/LandingPage.tsx, components/Navbar.tsx
- moved the sign in / up button to the navbar
=> Edited the splash page

utils/actions/storeActions.ts
a new store owner will go to the products page after creation
=> Add redirect new stores to products

app/shop/[shopSlug]/page.tsx, components/ShopStoreStory.tsx, components/StoreStory.tsx, lib/models/StoreStoryModel.ts, utils/actions/shopActions.ts
Adds the store's story to the shop page
Still TODO is better styling on the page, but this gets most of the components in place
=> Shop add store story

components/ShopProductItem.tsx, utils/actions/cartItemActions.ts
Add onclick handler for add to cart
=> Add add to cart button to store home page

app/shop/cart/page.tsx, components/Cart.tsx, components/ShopHeader.tsx, utils/actions/cartItemActions.ts, utils/actions/productActions.ts
Update getCartItems action
Add getShopProducts to Product Actions
=> Create cart page and component

lib/models/CartItemModel.ts, lib/models/OrderItemsModel.ts, lib/models/OrderModel.ts, utils/actions/cartActions.ts, utils/actions/orderActions.ts
Create get and create order actions
=> Create Order and Order Item model

app/orders/page.tsx, app/shop/orders/page.tsx, app/shop/process_order/page.tsx, components/CustomerOrders.tsx, utils/actions/cartActions.ts, utils/actions/orderActions.ts, utils/actions/productActions.ts
=> Add the ability to get customer orders

components/ShopHeader.tsx
Sign-in Button in Shop header now works with clerk sign in.
=> Adds clerk sign-in to shop header

components/ShopProductDetails.tsx, components/ShopProductItem.tsx
Swapped Add to cart functionality to use the same as from the ShopProductList page.
=> Connected add to cart button on product details card.

components/ShopProductDetails.tsx, components/ShopProductItem.tsx
Added toast message to bottom-center of ShopProductList and ShopProductItem pages after the Add to Cart button is clicked to provide feedback to the user that the item was added to their cart. 
https://github.com/ValentinaValverde/Pyme/assets/108947258/66818664-da13-4f86-8a0d-ee47ebfbacc3
=> Added toast message after item added to cart button click

app/shop/cart/page.tsx, components/Cart.tsx, utils/actions/cartItemActions.ts
Formatted cartItems into a table form using Material UI styling components.
=> Use MUI components to format a table for CartItems

app/shop/cart/page.tsx, components/Cart.tsx, utils/actions/cartItemActions.ts
Added delete buttons next to each cart item in the quantity portion of table. Functionality works. 
https://github.com/ValentinaValverde/Pyme/assets/108947258/2c0860b0-9d61-4453-936d-dafe53cdec85
=> Added delete button & functionality to cartItems

components/Cart.tsx, utils/actions/cartItemActions.ts
Added Material UI "plus icon" button to add items to cart functionality
https://github.com/ValentinaValverde/Pyme/assets/108947258/7d1e0d1b-d6f3-4a56-9d1b-2cb80e7b5f87
=> Added quantity edity functionality to cartItems

components/Cart.tsx
Added working subtotal card to Cart.tsx. Contains submit payment button (currently not hooked up). Added tooltip hover messages for delete and add items icons. 
https://github.com/ValentinaValverde/Pyme/assets/108947258/68194153-8f2e-44c2-b51f-dcc002a0e5b9
=> Added subtotal card w/ button and tooltip messages to Cart.tsx

app/mystore/[slug]/page.tsx, components/Cart.tsx, components/create-forms/CreateStoreStoryForm.tsx, components/edit-forms/EditStoreStoryForm.tsx
Font color changed from black to white for consistency and readability.
=> Changed font color on submit payment button t

components/Cart.tsx
=> Added total column to table and moved subtotal card to left

components/Cart.tsx
Changed Price to Price Per Item in column description and added $ before each price per item and total and total
=> Changed Price to per item and added $

components/Cart.tsx, components/ShopProductDetails.tsx, components/ShopProductItem.tsx, components/StoreOrders.tsx
Added .toFixed(2) to all prices that are listed on shop and myStore sites.
=> Added decimal places to prices throughout site

components/StoreOrders.tsx
Styled StoreOrders.tsx to look like CustomerOrders.tsx
=> Styled StoreOrders.tsx

app/shop/process_order/page.tsx
=> Changed text, style and location of message

components/Cart.tsx
=> Added decimals to subtotal card

components/Cart.tsx, components/QtyDropDown.tsx, utils/actions/cartItemActions.ts
A fully functional drop down to update qty in a users cart
=> Create dropdown to change qty in Cart.tsx

components/Cart.tsx, components/QtyDropDown.tsx, utils/actions/cartItemActions.ts
Add revalidate path when an to createCartItem
=> Add _deleteCartItem  to editCartItemQuantity

.github/workflows/main.yaml
Adds github actions workflow to repo so it will install packages and create a build to catch build errors before adding code to main.
=> Add github actions workflow

components/cart/Cart.tsx, components/create-forms/CreateProductForm.tsx, components/create-forms/CreateStoreAddressForm.tsx, components/create-forms/CreateStoreStoryForm.tsx, components/create-forms/StoreStoryForm.tsx
Changes made:
- Added aria-describedby for form instructions: Added a hidden paragraph to describe the form.
- Added htmlFor attribute to labels: Linked labels with their respective input fields using the htmlFor attribute.
- Added id to input fields: Ensured each input field has an id to match the label.
- Added aria-required to required fields: Specified which fields are required.
- Added aria-label to buttons: Provided clear labels for buttons to improve screen reader accessibility.
- These changes ensure the form is accessible and compliant with the latest WCAG guidelines.
To the following files:
-Cart.tsx
-CreateProductForm.tsx
-CreateStoreAddressForm.tsx
-CreateStoreStoryForm.tsx
-StoreStoryFrom.tsx
=> Add accessibility tags

components/edit-forms/EditProductForm.tsx, components/edit-forms/EditProductInvForm.tsx, components/edit-forms/EditStoreAddressForm.tsx, components/edit-forms/EditStoreStoryForm.tsx
Changes made:
- Added aria-describedby for form instructions: Included a hidden paragraph to describe the form.
- Added htmlFor attribute to labels: Linked labels with their respective input fields using the htmlFor attribute.
- Added id to input fields: Ensured each input field has an id to match the label.
- Added aria-required to required fields: Specified which fields are required.
- Added aria-label to buttons: Provided clear labels for buttons to improve screen reader accessibility.
- These changes ensure the form is accessible and compliant with the latest WCAG guidelines.
Changes made to the following files:
-  EditProductForm.tsx
-  EditProductInvForm.tsx
-  EditStoreAddressForm.tsx
-  EditStoreStoryForm.tsx
=> Added accessibility tags to forms

components/BusinessCardSection.tsx, components/CustomerOrders.tsx, components/Hero.tsx, components/ProductList.tsx, components/ShippingAddress.tsx, components/Sidebar.tsx, components/StoreSignUpForm.tsx, components/UpsertShippingAddressForm.tsx, components/featured-carousel/Carousel.tsx, components/featured-carousel/CarouselDots.tsx, components/shop/ShopAddToCart.tsx, components/shop/ShopHeader.tsx, components/shop/ShopProductDetails.tsx, components/shop/ShopProductItem.tsx, components/shop/ShopProductList.tsx, components/shop/ShopStoreStory.tsx
Changes made:
- Added aria-label to the submit button: Provided a clear label for the button to describe its action.
- Added aria-labelledby to the form: Linked the form to the heading to provide context.
- Added htmlFor and id to the input labels and fields: Linked the labels to the input fields for better accessibility.
- Added aria-required to the required input fields: Indicated that the fields are required for form submission.
These changes ensure the component is accessible and compliant with the latest WCAG guidelines.
Changes were made in the following files:
- components/BusinessCardSection.tsx
- components/CustomerOrders.tsx
- components/Hero.tsx
- components/ProductList.tsx
- components/ShippingAddress.tsx
- components/Sidebar.tsx
- components/StoreSignUpForm.tsx
- …
=> Added accessibility tags
